version: '3'
services:
  omni_api:
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - omni_postgres
      - omni_core
      - omni_engine
      - omni_redis
    links:
      - omni_postgres
      - omni_core
      - omni_redis
    networks:
      - Omni_Network
    ports:
      - "4005:80"
    labels:
      com.datadoghq.ad.logs: '[{"source": "omni-docker", "service": "omni-api"}]'

  omni_explorer:
    build:
      context: explorer
      dockerfile: Dockerfile
    depends_on:
      - omni_api
    links:
      - omni_api
    networks:
      - Omni_Network
    ports:
      - "4006:3000"
    labels:
      com.datadoghq.ad.logs: '[{"source": "omni-docker", "service": "omni-explorer"}]'

  #omni_core:
  #  build:
  #    context: core
  #    dockerfile: Dockerfile
  #  depends_on:
  #    - omni_engine
  #  volumes:
  #    - omnicore:/root/.omnixep
  #  ports:
  #    - "16818:18332"
  #  networks:
  #    - Omni_Network
  #  command: 
  #    -txindex
  #    -rpcuser=USER_RPC
  #    -rpcpassword=PASSWORD_RPC
  #    -rpcallowip=172.0.0.0/8
  #    -rpcport=16818
  #  labels:
  #    com.datadoghq.ad.logs: '[{"source": "omni-docker", "service": "omni-core"}]'

  omni_engine:
    build:
      context: engine
      dockerfile: Dockerfile
    depends_on:
      - omni_postgres
      - omni_core
      - omni_redis
    links:
      - omni_postgres
      - omni_core
      - omni_redis
    networks:
      - Omni_Network
    environment:
      FLYWAY_PLACEHOLDERS_OMNIAPIPASSWORD: omniapipass
      FLYWAY_PLACEHOLDERS_OMNIENGINEPASSWORD: omnienginepass
      PGUSER: postgres
      PGPASSWORD: postgresspass
      PGHOST: omni_postgres
      PGPORT: 5432
      OMNIDB_DATABASE: omni
      NETWORK: production
    labels:
      com.datadoghq.ad.logs: '[{"source": "omni-docker", "service": "omni-engine"}]'

  omni_postgres:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgresspass
      POSTGRES_DB: omni
    labels:
      com.datadoghq.ad.logs: '[{"source": "omni-docker", "service": "omni-postgres"}]'
    networks:
      - Omni_Network

  omni_redis:
    image: redis:alpine
    restart: always
    labels:
      com.datadoghq.ad.logs: '[{"source": "omni-docker", "service": "omni-redis"}]'
    networks:
      - Omni_Network

networks:
  Omni_Network:
    driver: bridge

volumes:
  pgdata:
  omnicore:
